/**
 * After Loop — LLM-based summary generation.
 *
 * Takes the extraction result and generates:
 *   1. A concise human-readable run summary (markdown)
 *   2. A structured JSON summary for programmatic use
 *
 * The summarizer template is a simple Handlebars-like format
 * (manual substitution, not full Handlebars — no external deps needed).
 */

import type { ExtractionResult } from "./extractor";

// ============================================================================
// Types
// ============================================================================

export interface RunSummary {
	/** Markdown summary for human reading. */
	markdown: string;
	/** Structured summary for programmatic use. */
	structured: SummaryData;
}

export interface SummaryData {
	runId: string;
	timestamp: string;
	status: string;
	iterations: number;
	workerCount: number;
	clonerCount: number;
	clonerApprovalRatio: number;
	topFindings: string[];
	keyInsights: string[];
	warnings: string[];
}

// ============================================================================
// Summarizer
// ============================================================================

/**
 * Generate a human-readable run summary from extraction results.
 *
 * This is a template-based approach. For production use, the summary
 * generation can be passed to the Cloner agent for LLM-based refinement.
 */
export function generateRunSummary(runId: string, result: ExtractionResult): RunSummary {
	const { lessons, stats } = result;

	// Categorize lessons
	const topFindings = lessons
		.filter(l => l.type === "insight")
		.map(l => l.summary)
		.slice(0, 5);

	const keyInsights = lessons
		.filter(l => l.type === "success")
		.map(l => l.summary)
		.slice(0, 3);

	const warnings = lessons
		.filter(l => l.type === "warning" || l.type === "error")
		.map(l => l.summary)
		.slice(0, 5);

	const timestamp = new Date().toISOString();

	const structured: SummaryData = {
		runId,
		timestamp,
		status: stats.finalStatus,
		iterations: stats.totalIterations,
		workerCount: stats.workerCount,
		clonerCount: stats.clonerCount,
		clonerApprovalRatio: stats.clonerApprovalRatio,
		topFindings,
		keyInsights,
		warnings,
	};

	const markdown = generateMarkdownSummary(structured, lessons.length);

	return { markdown, structured };
}

// ============================================================================
// Template
// ============================================================================

function generateMarkdownSummary(data: SummaryData, totalLessons: number): string {
	const statusEmoji =
		data.status === "completed" ? "✅" : data.status === "escalated" ? "⚠️" : data.status === "failed" ? "❌" : "⏹️";

	const lines = [
		`# Loop Engineering Run Summary`,
		``,
		`| Field | Value |`,
		`|-------|-------|`,
		`| Run ID | \`${data.runId}\` |`,
		`| Timestamp | ${data.timestamp} |`,
		`| Status | ${statusEmoji} ${data.status} |`,
		`| Iterations | ${data.iterations} |`,
		`| Workers | ${data.workerCount} |`,
		`| Cloners | ${data.clonerCount} |`,
		`| Cloner Approval Ratio | ${Math.round(data.clonerApprovalRatio * 100)}% |`,
		`| Lessons Extracted | ${totalLessons} |`,
		``,
	];

	if (data.keyInsights.length > 0) {
		lines.push(`## Key Insights`);
		lines.push(``);
		for (const insight of data.keyInsights) {
			lines.push(`- ✅ ${insight}`);
		}
		lines.push(``);
	}

	if (data.topFindings.length > 0) {
		lines.push(`## Top Findings`);
		lines.push(``);
		for (const finding of data.topFindings) {
			lines.push(`- ${finding}`);
		}
		lines.push(``);
	}

	if (data.warnings.length > 0) {
		lines.push(`## Warnings`);
		lines.push(``);
		for (const warning of data.warnings) {
			lines.push(`- ${data.status === "failed" ? "❌" : "⚠️"} ${warning}`);
		}
		lines.push(``);
	}

	lines.push(`## Statistics`);
	lines.push(``);
	lines.push(`- **Completion Rate**: ${data.status === "completed" ? "100%" : "0%"}`);
	lines.push(`- **Approval Trend**: ${formatApprovalTrend(data)}`);
	lines.push(``);
	lines.push(`---`);
	lines.push(`*Generated by Loop Engineering After Loop pipeline*`);

	return lines.join("\n");
}

function formatApprovalTrend(data: SummaryData): string {
	const ratio = data.clonerApprovalRatio;
	if (ratio >= 0.9) return `Strong consensus (${Math.round(ratio * 100)}% approval)`;
	if (ratio >= 0.7) return `Moderate agreement (${Math.round(ratio * 100)}% approval)`;
	if (ratio >= 0.5) return `Narrow majority (${Math.round(ratio * 100)}% approval)`;
	return `Low agreement (${Math.round(ratio * 100)}% approval)`;
}
